version: "3"

services:
  arangodb_dev:
    image: arangodb
    container_name: bolbeck_arangodb_dev
    env_file: docker-compose.env
    ports:
      - "8529:8529"
    volumes:
        - ./Arango/db:/var/lib/arangodb3
        - ./Arango/apps_db_system:/var/lib/arangodb3-apps/_db/
  graphql_server:
    build: ./GraphQLServer
    depends_on:
      - arangodb_dev
    container_name: bolbeck_graphserver_dev
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - ./GraphQLServer:/Bolbeck/code
    ports:
      - "8000:8000"
      - "5858:5858"
      - "4000:4000"
  ember_gui:
    image: danlynn/ember-cli
    container_name: bolbeck_ember_dev
    depends_on:
      - graphql_server
    volumes:
      - ./Ember:/myapp
    command: ember server
    ports:
      - "4200:4200"
      - "7020:7020"
      - "7357:7357"
